### ISSUE TITLE
Dynamic helpers

### ISSUE THREAD

**Issue by lille-morille** [lille-morille/moris_slave#1]
Math roles ending with "-helper", like "math-helper".
This should create a new subject with the prefix as the name "math-helper" -> "math".
Register this to the subjects list, for all applicable help.

Helper roles should be created when a new channel is created. Let's say you create the "⚽️-soccer" channel. The bot should create a "soccer-helper" role and add this as an option when using "/help".

When using "/help", a menu should pop up to create a new thread with a question in the respective channel.
Users should not be able to create conversations in these help channels, only through the bot's interface.

**Comment by RedRozio** [comment]
Side-note, users should be able to self-assign helper roles freely, to express their skill and contribute.
If this is not possible through discord's interface, a bot interface should be created for this like "/role".

**Comment by lille-morille** [comment]
users can now self-assign a helper role. next is to let them remove the role

**Comment by lille-morille** [comment]
Now all's left to do is to ping helpers when a new question is asked in a forum.
